# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/database.proto',
  package='database',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15protos/database.proto\x12\x08\x64\x61tabase\"_\n\x13ScriptHashCacheItem\x12\x13\n\x0bscript_hash\x18\x01 \x01(\x0c\x12\x15\n\rcached_status\x18\x02 \x01(\x0c\x12\x1c\n\x14\x63\x61\x63hed_status_height\x18\x03 \x01(\rb\x06proto3')
)




_SCRIPTHASHCACHEITEM = _descriptor.Descriptor(
  name='ScriptHashCacheItem',
  full_name='database.ScriptHashCacheItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='script_hash', full_name='database.ScriptHashCacheItem.script_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cached_status', full_name='database.ScriptHashCacheItem.cached_status', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cached_status_height', full_name='database.ScriptHashCacheItem.cached_status_height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['ScriptHashCacheItem'] = _SCRIPTHASHCACHEITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScriptHashCacheItem = _reflection.GeneratedProtocolMessageType('ScriptHashCacheItem', (_message.Message,), {
  'DESCRIPTOR' : _SCRIPTHASHCACHEITEM,
  '__module__' : 'protos.database_pb2'
  # @@protoc_insertion_point(class_scope:database.ScriptHashCacheItem)
  })
_sym_db.RegisterMessage(ScriptHashCacheItem)


# @@protoc_insertion_point(module_scope)
