# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protos/fee_estimation.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import protos.fee_estimation_pb2


class FeeEstimationBase(abc.ABC):

    @abc.abstractmethod
    async def EstimateFee(self, stream: 'grpclib.server.Stream[protos.fee_estimation_pb2.EstimateFeeRequest, protos.fee_estimation_pb2.EstimateFeeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RelayFee(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, protos.fee_estimation_pb2.RelayFeeResponse]') -> None:
        pass

    @abc.abstractmethod
    async def FeeHistogram(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, protos.fee_estimation_pb2.FeeHistogramResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/fee_estimation.FeeEstimation/EstimateFee': grpclib.const.Handler(
                self.EstimateFee,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.fee_estimation_pb2.EstimateFeeRequest,
                protos.fee_estimation_pb2.EstimateFeeResponse,
            ),
            '/fee_estimation.FeeEstimation/RelayFee': grpclib.const.Handler(
                self.RelayFee,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                protos.fee_estimation_pb2.RelayFeeResponse,
            ),
            '/fee_estimation.FeeEstimation/FeeHistogram': grpclib.const.Handler(
                self.FeeHistogram,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                protos.fee_estimation_pb2.FeeHistogramResponse,
            ),
        }


class FeeEstimationStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.EstimateFee = grpclib.client.UnaryUnaryMethod(
            channel,
            '/fee_estimation.FeeEstimation/EstimateFee',
            protos.fee_estimation_pb2.EstimateFeeRequest,
            protos.fee_estimation_pb2.EstimateFeeResponse,
        )
        self.RelayFee = grpclib.client.UnaryUnaryMethod(
            channel,
            '/fee_estimation.FeeEstimation/RelayFee',
            google.protobuf.empty_pb2.Empty,
            protos.fee_estimation_pb2.RelayFeeResponse,
        )
        self.FeeHistogram = grpclib.client.UnaryUnaryMethod(
            channel,
            '/fee_estimation.FeeEstimation/FeeHistogram',
            google.protobuf.empty_pb2.Empty,
            protos.fee_estimation_pb2.FeeHistogramResponse,
        )
