# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/fee_estimation.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/fee_estimation.proto',
  package='fee_estimation',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bprotos/fee_estimation.proto\x12\x0e\x66\x65\x65_estimation\x1a\x1bgoogle/protobuf/empty.proto\"$\n\x12\x45stimateFeeRequest\x12\x0e\n\x06number\x18\x01 \x01(\r\"\"\n\x13\x45stimateFeeResponse\x12\x0b\n\x03\x66\x65\x65\x18\x01 \x01(\x01\"\x1f\n\x10RelayFeeResponse\x12\x0b\n\x03\x66\x65\x65\x18\x01 \x01(\x01\"z\n\x14\x46\x65\x65HistogramResponse\x12;\n\x05pairs\x18\x01 \x03(\x0b\x32,.fee_estimation.FeeHistogramResponse.FeePair\x1a%\n\x07\x46\x65\x65Pair\x12\x0b\n\x03\x66\x65\x65\x18\x01 \x01(\x01\x12\r\n\x05vsize\x18\x02 \x01(\r2\xfb\x01\n\rFeeEstimation\x12V\n\x0b\x45stimateFee\x12\".fee_estimation.EstimateFeeRequest\x1a#.fee_estimation.EstimateFeeResponse\x12\x44\n\x08RelayFee\x12\x16.google.protobuf.Empty\x1a .fee_estimation.RelayFeeResponse\x12L\n\x0c\x46\x65\x65Histogram\x12\x16.google.protobuf.Empty\x1a$.fee_estimation.FeeHistogramResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ESTIMATEFEEREQUEST = _descriptor.Descriptor(
  name='EstimateFeeRequest',
  full_name='fee_estimation.EstimateFeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='fee_estimation.EstimateFeeRequest.number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=112,
)


_ESTIMATEFEERESPONSE = _descriptor.Descriptor(
  name='EstimateFeeResponse',
  full_name='fee_estimation.EstimateFeeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fee', full_name='fee_estimation.EstimateFeeResponse.fee', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=148,
)


_RELAYFEERESPONSE = _descriptor.Descriptor(
  name='RelayFeeResponse',
  full_name='fee_estimation.RelayFeeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fee', full_name='fee_estimation.RelayFeeResponse.fee', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=181,
)


_FEEHISTOGRAMRESPONSE_FEEPAIR = _descriptor.Descriptor(
  name='FeePair',
  full_name='fee_estimation.FeeHistogramResponse.FeePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fee', full_name='fee_estimation.FeeHistogramResponse.FeePair.fee', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vsize', full_name='fee_estimation.FeeHistogramResponse.FeePair.vsize', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=305,
)

_FEEHISTOGRAMRESPONSE = _descriptor.Descriptor(
  name='FeeHistogramResponse',
  full_name='fee_estimation.FeeHistogramResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairs', full_name='fee_estimation.FeeHistogramResponse.pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FEEHISTOGRAMRESPONSE_FEEPAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=305,
)

_FEEHISTOGRAMRESPONSE_FEEPAIR.containing_type = _FEEHISTOGRAMRESPONSE
_FEEHISTOGRAMRESPONSE.fields_by_name['pairs'].message_type = _FEEHISTOGRAMRESPONSE_FEEPAIR
DESCRIPTOR.message_types_by_name['EstimateFeeRequest'] = _ESTIMATEFEEREQUEST
DESCRIPTOR.message_types_by_name['EstimateFeeResponse'] = _ESTIMATEFEERESPONSE
DESCRIPTOR.message_types_by_name['RelayFeeResponse'] = _RELAYFEERESPONSE
DESCRIPTOR.message_types_by_name['FeeHistogramResponse'] = _FEEHISTOGRAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EstimateFeeRequest = _reflection.GeneratedProtocolMessageType('EstimateFeeRequest', (_message.Message,), {
  'DESCRIPTOR' : _ESTIMATEFEEREQUEST,
  '__module__' : 'protos.fee_estimation_pb2'
  # @@protoc_insertion_point(class_scope:fee_estimation.EstimateFeeRequest)
  })
_sym_db.RegisterMessage(EstimateFeeRequest)

EstimateFeeResponse = _reflection.GeneratedProtocolMessageType('EstimateFeeResponse', (_message.Message,), {
  'DESCRIPTOR' : _ESTIMATEFEERESPONSE,
  '__module__' : 'protos.fee_estimation_pb2'
  # @@protoc_insertion_point(class_scope:fee_estimation.EstimateFeeResponse)
  })
_sym_db.RegisterMessage(EstimateFeeResponse)

RelayFeeResponse = _reflection.GeneratedProtocolMessageType('RelayFeeResponse', (_message.Message,), {
  'DESCRIPTOR' : _RELAYFEERESPONSE,
  '__module__' : 'protos.fee_estimation_pb2'
  # @@protoc_insertion_point(class_scope:fee_estimation.RelayFeeResponse)
  })
_sym_db.RegisterMessage(RelayFeeResponse)

FeeHistogramResponse = _reflection.GeneratedProtocolMessageType('FeeHistogramResponse', (_message.Message,), {

  'FeePair' : _reflection.GeneratedProtocolMessageType('FeePair', (_message.Message,), {
    'DESCRIPTOR' : _FEEHISTOGRAMRESPONSE_FEEPAIR,
    '__module__' : 'protos.fee_estimation_pb2'
    # @@protoc_insertion_point(class_scope:fee_estimation.FeeHistogramResponse.FeePair)
    })
  ,
  'DESCRIPTOR' : _FEEHISTOGRAMRESPONSE,
  '__module__' : 'protos.fee_estimation_pb2'
  # @@protoc_insertion_point(class_scope:fee_estimation.FeeHistogramResponse)
  })
_sym_db.RegisterMessage(FeeHistogramResponse)
_sym_db.RegisterMessage(FeeHistogramResponse.FeePair)



_FEEESTIMATION = _descriptor.ServiceDescriptor(
  name='FeeEstimation',
  full_name='fee_estimation.FeeEstimation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=308,
  serialized_end=559,
  methods=[
  _descriptor.MethodDescriptor(
    name='EstimateFee',
    full_name='fee_estimation.FeeEstimation.EstimateFee',
    index=0,
    containing_service=None,
    input_type=_ESTIMATEFEEREQUEST,
    output_type=_ESTIMATEFEERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RelayFee',
    full_name='fee_estimation.FeeEstimation.RelayFee',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_RELAYFEERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FeeHistogram',
    full_name='fee_estimation.FeeEstimation.FeeHistogram',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_FEEHISTOGRAMRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FEEESTIMATION)

DESCRIPTOR.services_by_name['FeeEstimation'] = _FEEESTIMATION

# @@protoc_insertion_point(module_scope)
