# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/header.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/header.proto',
  package='header',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13protos/header.proto\x12\x06header\x1a\x1bgoogle/protobuf/empty.proto\"H\n\x0eHeadersRequest\x12\x14\n\x0cstart_height\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\r\x12\x11\n\tcp_height\x18\x03 \x01(\r\"@\n\x0fHeadersResponse\x12\x0f\n\x07headers\x18\x01 \x03(\x0c\x12\x0c\n\x04root\x18\x02 \x01(\x0c\x12\x0e\n\x06\x62ranch\x18\x03 \x03(\x0c\"3\n\x11SubscribeResponse\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\r2\x87\x01\n\x07Headers\x12:\n\x07Headers\x12\x16.header.HeadersRequest\x1a\x17.header.HeadersResponse\x12@\n\tSubscribe\x12\x16.google.protobuf.Empty\x1a\x19.header.SubscribeResponse0\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_HEADERSREQUEST = _descriptor.Descriptor(
  name='HeadersRequest',
  full_name='header.HeadersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_height', full_name='header.HeadersRequest.start_height', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='header.HeadersRequest.count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cp_height', full_name='header.HeadersRequest.cp_height', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=132,
)


_HEADERSRESPONSE = _descriptor.Descriptor(
  name='HeadersResponse',
  full_name='header.HeadersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headers', full_name='header.HeadersResponse.headers', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root', full_name='header.HeadersResponse.root', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='branch', full_name='header.HeadersResponse.branch', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=198,
)


_SUBSCRIBERESPONSE = _descriptor.Descriptor(
  name='SubscribeResponse',
  full_name='header.SubscribeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='header.SubscribeResponse.header', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='header.SubscribeResponse.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=251,
)

DESCRIPTOR.message_types_by_name['HeadersRequest'] = _HEADERSREQUEST
DESCRIPTOR.message_types_by_name['HeadersResponse'] = _HEADERSRESPONSE
DESCRIPTOR.message_types_by_name['SubscribeResponse'] = _SUBSCRIBERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HeadersRequest = _reflection.GeneratedProtocolMessageType('HeadersRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEADERSREQUEST,
  '__module__' : 'protos.header_pb2'
  # @@protoc_insertion_point(class_scope:header.HeadersRequest)
  })
_sym_db.RegisterMessage(HeadersRequest)

HeadersResponse = _reflection.GeneratedProtocolMessageType('HeadersResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEADERSRESPONSE,
  '__module__' : 'protos.header_pb2'
  # @@protoc_insertion_point(class_scope:header.HeadersResponse)
  })
_sym_db.RegisterMessage(HeadersResponse)

SubscribeResponse = _reflection.GeneratedProtocolMessageType('SubscribeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBERESPONSE,
  '__module__' : 'protos.header_pb2'
  # @@protoc_insertion_point(class_scope:header.SubscribeResponse)
  })
_sym_db.RegisterMessage(SubscribeResponse)



_HEADERS = _descriptor.ServiceDescriptor(
  name='Headers',
  full_name='header.Headers',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=254,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='Headers',
    full_name='header.Headers.Headers',
    index=0,
    containing_service=None,
    input_type=_HEADERSREQUEST,
    output_type=_HEADERSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Subscribe',
    full_name='header.Headers.Subscribe',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SUBSCRIBERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HEADERS)

DESCRIPTOR.services_by_name['Headers'] = _HEADERS

# @@protoc_insertion_point(module_scope)
