# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transaction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/transaction.proto',
  package='transaction',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18protos/transaction.proto\x12\x0btransaction\"\"\n\x10\x42roadcastRequest\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\"$\n\x11\x42roadcastResponse\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\"E\n\x12TransactionRequest\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0e\n\x06merkle\x18\x03 \x01(\x08\"\xa7\x01\n\x13TransactionResponse\x12\x0e\n\x06raw_tx\x18\x01 \x01(\x0c\x12=\n\x06merkle\x18\x02 \x01(\x0b\x32-.transaction.TransactionResponse.TxMerkleInfo\x1a\x41\n\x0cTxMerkleInfo\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\r\x12\x0e\n\x06merkle\x18\x02 \x03(\x0c\x12\x0b\n\x03pos\x18\x03 \x01(\r\"&\n\x13MerkleBranchRequest\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\"I\n\x14MerkleBranchResponse\x12\x14\n\x0c\x62lock_height\x18\x01 \x01(\r\x12\x0e\n\x06merkle\x18\x02 \x03(\x0c\x12\x0b\n\x03pos\x18\x03 \x01(\r\"B\n\x10IdFromPosRequest\x12\x0e\n\x06height\x18\x01 \x01(\r\x12\x0e\n\x06tx_pos\x18\x02 \x01(\r\x12\x0e\n\x06merkle\x18\x03 \x01(\x08\"4\n\x11IdFromPosResponse\x12\x0f\n\x07tx_hash\x18\x01 \x01(\x0c\x12\x0e\n\x06merkle\x18\x02 \x03(\x0c\x32\xcc\x02\n\x0bTransaction\x12J\n\tBroadcast\x12\x1d.transaction.BroadcastRequest\x1a\x1e.transaction.BroadcastResponse\x12P\n\x0bTransaction\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponse\x12S\n\x0cMerkleBranch\x12 .transaction.MerkleBranchRequest\x1a!.transaction.MerkleBranchResponse\x12J\n\tIdFromPos\x12\x1d.transaction.IdFromPosRequest\x1a\x1e.transaction.IdFromPosResponseb\x06proto3')
)




_BROADCASTREQUEST = _descriptor.Descriptor(
  name='BroadcastRequest',
  full_name='transaction.BroadcastRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_tx', full_name='transaction.BroadcastRequest.raw_tx', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=75,
)


_BROADCASTRESPONSE = _descriptor.Descriptor(
  name='BroadcastResponse',
  full_name='transaction.BroadcastResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='transaction.BroadcastResponse.tx_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=113,
)


_TRANSACTIONREQUEST = _descriptor.Descriptor(
  name='TransactionRequest',
  full_name='transaction.TransactionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='transaction.TransactionRequest.tx_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='transaction.TransactionRequest.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='transaction.TransactionRequest.merkle', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=184,
)


_TRANSACTIONRESPONSE_TXMERKLEINFO = _descriptor.Descriptor(
  name='TxMerkleInfo',
  full_name='transaction.TransactionResponse.TxMerkleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_height', full_name='transaction.TransactionResponse.TxMerkleInfo.block_height', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='transaction.TransactionResponse.TxMerkleInfo.merkle', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='transaction.TransactionResponse.TxMerkleInfo.pos', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=354,
)

_TRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='TransactionResponse',
  full_name='transaction.TransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_tx', full_name='transaction.TransactionResponse.raw_tx', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='transaction.TransactionResponse.merkle', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRANSACTIONRESPONSE_TXMERKLEINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=354,
)


_MERKLEBRANCHREQUEST = _descriptor.Descriptor(
  name='MerkleBranchRequest',
  full_name='transaction.MerkleBranchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='transaction.MerkleBranchRequest.tx_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=394,
)


_MERKLEBRANCHRESPONSE = _descriptor.Descriptor(
  name='MerkleBranchResponse',
  full_name='transaction.MerkleBranchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_height', full_name='transaction.MerkleBranchResponse.block_height', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='transaction.MerkleBranchResponse.merkle', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='transaction.MerkleBranchResponse.pos', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=396,
  serialized_end=469,
)


_IDFROMPOSREQUEST = _descriptor.Descriptor(
  name='IdFromPosRequest',
  full_name='transaction.IdFromPosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='transaction.IdFromPosRequest.height', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_pos', full_name='transaction.IdFromPosRequest.tx_pos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='transaction.IdFromPosRequest.merkle', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=471,
  serialized_end=537,
)


_IDFROMPOSRESPONSE = _descriptor.Descriptor(
  name='IdFromPosResponse',
  full_name='transaction.IdFromPosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tx_hash', full_name='transaction.IdFromPosResponse.tx_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='merkle', full_name='transaction.IdFromPosResponse.merkle', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=539,
  serialized_end=591,
)

_TRANSACTIONRESPONSE_TXMERKLEINFO.containing_type = _TRANSACTIONRESPONSE
_TRANSACTIONRESPONSE.fields_by_name['merkle'].message_type = _TRANSACTIONRESPONSE_TXMERKLEINFO
DESCRIPTOR.message_types_by_name['BroadcastRequest'] = _BROADCASTREQUEST
DESCRIPTOR.message_types_by_name['BroadcastResponse'] = _BROADCASTRESPONSE
DESCRIPTOR.message_types_by_name['TransactionRequest'] = _TRANSACTIONREQUEST
DESCRIPTOR.message_types_by_name['TransactionResponse'] = _TRANSACTIONRESPONSE
DESCRIPTOR.message_types_by_name['MerkleBranchRequest'] = _MERKLEBRANCHREQUEST
DESCRIPTOR.message_types_by_name['MerkleBranchResponse'] = _MERKLEBRANCHRESPONSE
DESCRIPTOR.message_types_by_name['IdFromPosRequest'] = _IDFROMPOSREQUEST
DESCRIPTOR.message_types_by_name['IdFromPosResponse'] = _IDFROMPOSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BroadcastRequest = _reflection.GeneratedProtocolMessageType('BroadcastRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTREQUEST,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.BroadcastRequest)
  })
_sym_db.RegisterMessage(BroadcastRequest)

BroadcastResponse = _reflection.GeneratedProtocolMessageType('BroadcastResponse', (_message.Message,), {
  'DESCRIPTOR' : _BROADCASTRESPONSE,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.BroadcastResponse)
  })
_sym_db.RegisterMessage(BroadcastResponse)

TransactionRequest = _reflection.GeneratedProtocolMessageType('TransactionRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONREQUEST,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.TransactionRequest)
  })
_sym_db.RegisterMessage(TransactionRequest)

TransactionResponse = _reflection.GeneratedProtocolMessageType('TransactionResponse', (_message.Message,), {

  'TxMerkleInfo' : _reflection.GeneratedProtocolMessageType('TxMerkleInfo', (_message.Message,), {
    'DESCRIPTOR' : _TRANSACTIONRESPONSE_TXMERKLEINFO,
    '__module__' : 'protos.transaction_pb2'
    # @@protoc_insertion_point(class_scope:transaction.TransactionResponse.TxMerkleInfo)
    })
  ,
  'DESCRIPTOR' : _TRANSACTIONRESPONSE,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.TransactionResponse)
  })
_sym_db.RegisterMessage(TransactionResponse)
_sym_db.RegisterMessage(TransactionResponse.TxMerkleInfo)

MerkleBranchRequest = _reflection.GeneratedProtocolMessageType('MerkleBranchRequest', (_message.Message,), {
  'DESCRIPTOR' : _MERKLEBRANCHREQUEST,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.MerkleBranchRequest)
  })
_sym_db.RegisterMessage(MerkleBranchRequest)

MerkleBranchResponse = _reflection.GeneratedProtocolMessageType('MerkleBranchResponse', (_message.Message,), {
  'DESCRIPTOR' : _MERKLEBRANCHRESPONSE,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.MerkleBranchResponse)
  })
_sym_db.RegisterMessage(MerkleBranchResponse)

IdFromPosRequest = _reflection.GeneratedProtocolMessageType('IdFromPosRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDFROMPOSREQUEST,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.IdFromPosRequest)
  })
_sym_db.RegisterMessage(IdFromPosRequest)

IdFromPosResponse = _reflection.GeneratedProtocolMessageType('IdFromPosResponse', (_message.Message,), {
  'DESCRIPTOR' : _IDFROMPOSRESPONSE,
  '__module__' : 'protos.transaction_pb2'
  # @@protoc_insertion_point(class_scope:transaction.IdFromPosResponse)
  })
_sym_db.RegisterMessage(IdFromPosResponse)



_TRANSACTION = _descriptor.ServiceDescriptor(
  name='Transaction',
  full_name='transaction.Transaction',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=594,
  serialized_end=926,
  methods=[
  _descriptor.MethodDescriptor(
    name='Broadcast',
    full_name='transaction.Transaction.Broadcast',
    index=0,
    containing_service=None,
    input_type=_BROADCASTREQUEST,
    output_type=_BROADCASTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Transaction',
    full_name='transaction.Transaction.Transaction',
    index=1,
    containing_service=None,
    input_type=_TRANSACTIONREQUEST,
    output_type=_TRANSACTIONRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MerkleBranch',
    full_name='transaction.Transaction.MerkleBranch',
    index=2,
    containing_service=None,
    input_type=_MERKLEBRANCHREQUEST,
    output_type=_MERKLEBRANCHRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IdFromPos',
    full_name='transaction.Transaction.IdFromPos',
    index=3,
    containing_service=None,
    input_type=_IDFROMPOSREQUEST,
    output_type=_IDFROMPOSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRANSACTION)

DESCRIPTOR.services_by_name['Transaction'] = _TRANSACTION

# @@protoc_insertion_point(module_scope)
