# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/utility.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/utility.proto',
  package='utility',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14protos/utility.proto\x12\x07utility\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0e\x42\x61nnerResponse\x12\x0e\n\x06\x62\x61nner\x18\x01 \x01(\t\"*\n\x17\x44onationAddressResponse\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"0\n\x0eVersionRequest\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"1\n\x0fVersionResponse\x12\r\n\x05\x61gent\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\x87\x02\n\x07Utility\x12\x39\n\x06\x42\x61nner\x12\x16.google.protobuf.Empty\x1a\x17.utility.BannerResponse\x12K\n\x0f\x44onationAddress\x12\x16.google.protobuf.Empty\x1a .utility.DonationAddressResponse\x12\x36\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12<\n\x07Version\x12\x17.utility.VersionRequest\x1a\x18.utility.VersionResponseb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_BANNERRESPONSE = _descriptor.Descriptor(
  name='BannerResponse',
  full_name='utility.BannerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='banner', full_name='utility.BannerResponse.banner', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=94,
)


_DONATIONADDRESSRESPONSE = _descriptor.Descriptor(
  name='DonationAddressResponse',
  full_name='utility.DonationAddressResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='utility.DonationAddressResponse.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=138,
)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='utility.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='utility.VersionRequest.agent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='utility.VersionRequest.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=188,
)


_VERSIONRESPONSE = _descriptor.Descriptor(
  name='VersionResponse',
  full_name='utility.VersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent', full_name='utility.VersionResponse.agent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='utility.VersionResponse.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=239,
)

DESCRIPTOR.message_types_by_name['BannerResponse'] = _BANNERRESPONSE
DESCRIPTOR.message_types_by_name['DonationAddressResponse'] = _DONATIONADDRESSRESPONSE
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionResponse'] = _VERSIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BannerResponse = _reflection.GeneratedProtocolMessageType('BannerResponse', (_message.Message,), {
  'DESCRIPTOR' : _BANNERRESPONSE,
  '__module__' : 'protos.utility_pb2'
  # @@protoc_insertion_point(class_scope:utility.BannerResponse)
  })
_sym_db.RegisterMessage(BannerResponse)

DonationAddressResponse = _reflection.GeneratedProtocolMessageType('DonationAddressResponse', (_message.Message,), {
  'DESCRIPTOR' : _DONATIONADDRESSRESPONSE,
  '__module__' : 'protos.utility_pb2'
  # @@protoc_insertion_point(class_scope:utility.DonationAddressResponse)
  })
_sym_db.RegisterMessage(DonationAddressResponse)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONREQUEST,
  '__module__' : 'protos.utility_pb2'
  # @@protoc_insertion_point(class_scope:utility.VersionRequest)
  })
_sym_db.RegisterMessage(VersionRequest)

VersionResponse = _reflection.GeneratedProtocolMessageType('VersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONRESPONSE,
  '__module__' : 'protos.utility_pb2'
  # @@protoc_insertion_point(class_scope:utility.VersionResponse)
  })
_sym_db.RegisterMessage(VersionResponse)



_UTILITY = _descriptor.ServiceDescriptor(
  name='Utility',
  full_name='utility.Utility',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=242,
  serialized_end=505,
  methods=[
  _descriptor.MethodDescriptor(
    name='Banner',
    full_name='utility.Utility.Banner',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BANNERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DonationAddress',
    full_name='utility.Utility.DonationAddress',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_DONATIONADDRESSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='utility.Utility.Ping',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Version',
    full_name='utility.Utility.Version',
    index=3,
    containing_service=None,
    input_type=_VERSIONREQUEST,
    output_type=_VERSIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UTILITY)

DESCRIPTOR.services_by_name['Utility'] = _UTILITY

# @@protoc_insertion_point(module_scope)
