# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protos/utility.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import google.protobuf.empty_pb2
import protos.utility_pb2


class UtilityBase(abc.ABC):

    @abc.abstractmethod
    async def Banner(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, protos.utility_pb2.BannerResponse]') -> None:
        pass

    @abc.abstractmethod
    async def DonationAddress(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, protos.utility_pb2.DonationAddressResponse]') -> None:
        pass

    @abc.abstractmethod
    async def Ping(self, stream: 'grpclib.server.Stream[google.protobuf.empty_pb2.Empty, google.protobuf.empty_pb2.Empty]') -> None:
        pass

    @abc.abstractmethod
    async def Version(self, stream: 'grpclib.server.Stream[protos.utility_pb2.VersionRequest, protos.utility_pb2.VersionResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/utility.Utility/Banner': grpclib.const.Handler(
                self.Banner,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                protos.utility_pb2.BannerResponse,
            ),
            '/utility.Utility/DonationAddress': grpclib.const.Handler(
                self.DonationAddress,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                protos.utility_pb2.DonationAddressResponse,
            ),
            '/utility.Utility/Ping': grpclib.const.Handler(
                self.Ping,
                grpclib.const.Cardinality.UNARY_UNARY,
                google.protobuf.empty_pb2.Empty,
                google.protobuf.empty_pb2.Empty,
            ),
            '/utility.Utility/Version': grpclib.const.Handler(
                self.Version,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.utility_pb2.VersionRequest,
                protos.utility_pb2.VersionResponse,
            ),
        }


class UtilityStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Banner = grpclib.client.UnaryUnaryMethod(
            channel,
            '/utility.Utility/Banner',
            google.protobuf.empty_pb2.Empty,
            protos.utility_pb2.BannerResponse,
        )
        self.DonationAddress = grpclib.client.UnaryUnaryMethod(
            channel,
            '/utility.Utility/DonationAddress',
            google.protobuf.empty_pb2.Empty,
            protos.utility_pb2.DonationAddressResponse,
        )
        self.Ping = grpclib.client.UnaryUnaryMethod(
            channel,
            '/utility.Utility/Ping',
            google.protobuf.empty_pb2.Empty,
            google.protobuf.empty_pb2.Empty,
        )
        self.Version = grpclib.client.UnaryUnaryMethod(
            channel,
            '/utility.Utility/Version',
            protos.utility_pb2.VersionRequest,
            protos.utility_pb2.VersionResponse,
        )
