# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/wist_list.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/wist_list.proto',
  package='wish_list',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16protos/wist_list.proto\x12\twish_list\"_\n\x0eTXOInfoRequest\x12+\n\x04txos\x18\x01 \x03(\x0b\x32\x1d.wish_list.TXOInfoRequest.TXO\x1a \n\x03TXO\x12\x0c\n\x04txid\x18\x01 \x01(\x0c\x12\x0b\n\x03pos\x18\x02 \x01(\r\"\xa7\x02\n\x0fTXOInfoResponse\x12\x32\n\x04txos\x18\x01 \x03(\x0b\x32$.wish_list.TXOInfoResponse.TxosEntry\x1a\x8e\x01\n\x07TXOInfo\x12\x0e\n\x06script\x18\x01 \x01(\x0c\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12;\n\x05spent\x18\x03 \x01(\x0b\x32,.wish_list.TXOInfoResponse.TXOInfo.SpentInfo\x1a&\n\tSpentInfo\x12\x0c\n\x04txid\x18\x01 \x01(\x0c\x12\x0b\n\x03pos\x18\x02 \x01(\r\x1aO\n\tTxosEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\x31\n\x05value\x18\x02 \x01(\x0b\x32\".wish_list.TXOInfoResponse.TXOInfo:\x02\x38\x01\x32L\n\x08WishList\x12@\n\x07TXOInfo\x12\x19.wish_list.TXOInfoRequest\x1a\x1a.wish_list.TXOInfoResponseb\x06proto3')
)




_TXOINFOREQUEST_TXO = _descriptor.Descriptor(
  name='TXO',
  full_name='wish_list.TXOInfoRequest.TXO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txid', full_name='wish_list.TXOInfoRequest.TXO.txid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='wish_list.TXOInfoRequest.TXO.pos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=132,
)

_TXOINFOREQUEST = _descriptor.Descriptor(
  name='TXOInfoRequest',
  full_name='wish_list.TXOInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txos', full_name='wish_list.TXOInfoRequest.txos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TXOINFOREQUEST_TXO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=132,
)


_TXOINFORESPONSE_TXOINFO_SPENTINFO = _descriptor.Descriptor(
  name='SpentInfo',
  full_name='wish_list.TXOInfoResponse.TXOInfo.SpentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txid', full_name='wish_list.TXOInfoResponse.TXOInfo.SpentInfo.txid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='wish_list.TXOInfoResponse.TXOInfo.SpentInfo.pos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=349,
)

_TXOINFORESPONSE_TXOINFO = _descriptor.Descriptor(
  name='TXOInfo',
  full_name='wish_list.TXOInfoResponse.TXOInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='script', full_name='wish_list.TXOInfoResponse.TXOInfo.script', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='wish_list.TXOInfoResponse.TXOInfo.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='spent', full_name='wish_list.TXOInfoResponse.TXOInfo.spent', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TXOINFORESPONSE_TXOINFO_SPENTINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=349,
)

_TXOINFORESPONSE_TXOSENTRY = _descriptor.Descriptor(
  name='TxosEntry',
  full_name='wish_list.TXOInfoResponse.TxosEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='wish_list.TXOInfoResponse.TxosEntry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='wish_list.TXOInfoResponse.TxosEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=430,
)

_TXOINFORESPONSE = _descriptor.Descriptor(
  name='TXOInfoResponse',
  full_name='wish_list.TXOInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='txos', full_name='wish_list.TXOInfoResponse.txos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TXOINFORESPONSE_TXOINFO, _TXOINFORESPONSE_TXOSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=430,
)

_TXOINFOREQUEST_TXO.containing_type = _TXOINFOREQUEST
_TXOINFOREQUEST.fields_by_name['txos'].message_type = _TXOINFOREQUEST_TXO
_TXOINFORESPONSE_TXOINFO_SPENTINFO.containing_type = _TXOINFORESPONSE_TXOINFO
_TXOINFORESPONSE_TXOINFO.fields_by_name['spent'].message_type = _TXOINFORESPONSE_TXOINFO_SPENTINFO
_TXOINFORESPONSE_TXOINFO.containing_type = _TXOINFORESPONSE
_TXOINFORESPONSE_TXOSENTRY.fields_by_name['value'].message_type = _TXOINFORESPONSE_TXOINFO
_TXOINFORESPONSE_TXOSENTRY.containing_type = _TXOINFORESPONSE
_TXOINFORESPONSE.fields_by_name['txos'].message_type = _TXOINFORESPONSE_TXOSENTRY
DESCRIPTOR.message_types_by_name['TXOInfoRequest'] = _TXOINFOREQUEST
DESCRIPTOR.message_types_by_name['TXOInfoResponse'] = _TXOINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TXOInfoRequest = _reflection.GeneratedProtocolMessageType('TXOInfoRequest', (_message.Message,), {

  'TXO' : _reflection.GeneratedProtocolMessageType('TXO', (_message.Message,), {
    'DESCRIPTOR' : _TXOINFOREQUEST_TXO,
    '__module__' : 'protos.wist_list_pb2'
    # @@protoc_insertion_point(class_scope:wish_list.TXOInfoRequest.TXO)
    })
  ,
  'DESCRIPTOR' : _TXOINFOREQUEST,
  '__module__' : 'protos.wist_list_pb2'
  # @@protoc_insertion_point(class_scope:wish_list.TXOInfoRequest)
  })
_sym_db.RegisterMessage(TXOInfoRequest)
_sym_db.RegisterMessage(TXOInfoRequest.TXO)

TXOInfoResponse = _reflection.GeneratedProtocolMessageType('TXOInfoResponse', (_message.Message,), {

  'TXOInfo' : _reflection.GeneratedProtocolMessageType('TXOInfo', (_message.Message,), {

    'SpentInfo' : _reflection.GeneratedProtocolMessageType('SpentInfo', (_message.Message,), {
      'DESCRIPTOR' : _TXOINFORESPONSE_TXOINFO_SPENTINFO,
      '__module__' : 'protos.wist_list_pb2'
      # @@protoc_insertion_point(class_scope:wish_list.TXOInfoResponse.TXOInfo.SpentInfo)
      })
    ,
    'DESCRIPTOR' : _TXOINFORESPONSE_TXOINFO,
    '__module__' : 'protos.wist_list_pb2'
    # @@protoc_insertion_point(class_scope:wish_list.TXOInfoResponse.TXOInfo)
    })
  ,

  'TxosEntry' : _reflection.GeneratedProtocolMessageType('TxosEntry', (_message.Message,), {
    'DESCRIPTOR' : _TXOINFORESPONSE_TXOSENTRY,
    '__module__' : 'protos.wist_list_pb2'
    # @@protoc_insertion_point(class_scope:wish_list.TXOInfoResponse.TxosEntry)
    })
  ,
  'DESCRIPTOR' : _TXOINFORESPONSE,
  '__module__' : 'protos.wist_list_pb2'
  # @@protoc_insertion_point(class_scope:wish_list.TXOInfoResponse)
  })
_sym_db.RegisterMessage(TXOInfoResponse)
_sym_db.RegisterMessage(TXOInfoResponse.TXOInfo)
_sym_db.RegisterMessage(TXOInfoResponse.TXOInfo.SpentInfo)
_sym_db.RegisterMessage(TXOInfoResponse.TxosEntry)


_TXOINFORESPONSE_TXOSENTRY._options = None

_WISHLIST = _descriptor.ServiceDescriptor(
  name='WishList',
  full_name='wish_list.WishList',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=432,
  serialized_end=508,
  methods=[
  _descriptor.MethodDescriptor(
    name='TXOInfo',
    full_name='wish_list.WishList.TXOInfo',
    index=0,
    containing_service=None,
    input_type=_TXOINFOREQUEST,
    output_type=_TXOINFORESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WISHLIST)

DESCRIPTOR.services_by_name['WishList'] = _WISHLIST

# @@protoc_insertion_point(module_scope)
