# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protos/wist_list.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import protos.wist_list_pb2


class WishListBase(abc.ABC):

    @abc.abstractmethod
    async def TXOInfo(self, stream: 'grpclib.server.Stream[protos.wist_list_pb2.TXOInfoRequest, protos.wist_list_pb2.TXOInfoResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/wish_list.WishList/TXOInfo': grpclib.const.Handler(
                self.TXOInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                protos.wist_list_pb2.TXOInfoRequest,
                protos.wist_list_pb2.TXOInfoResponse,
            ),
        }


class WishListStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.TXOInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/wish_list.WishList/TXOInfo',
            protos.wist_list_pb2.TXOInfoRequest,
            protos.wist_list_pb2.TXOInfoResponse,
        )
